### ISSUE TITLE
Any public container registry available for the docker?

### ISSUE THREAD

**Issue by charlesa101** [hex108/cron-hpa-controller#1]
Is there any public container registry available for this? 

{{ .Values.image.repository }}/kube-batch:{{ .Values.image.tag }}

**Comment by hex108** [comment]
@charlesa101 Sorry for late reply. You could get it from https://cloud.docker.com/u/hex108/repository/docker/hex108/cron-hpa-controller now.

`docker pull hex108/cron-hpa-controller`
